theme: jekyll-theme-minimal
title: lipu lipamanka
description: lipamanaka's website, shared by lipamanka and a few other people
image: http://lipamanka.gay/images/lipamanka.png

defaults:
  - scope:
      path: ""
    values:
      layout: "nasin"